Form validation
MMhaidari/portfolio-setup-and-mobile-first pull request #9
Opened 2023-02-01 12:22 UTC by MMhaidari

# What is added new
- form validation is added to the project

2023-02-01 12:57 UTC, mwanawabangona requested changes
Hi @MMhaidari ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a `Wrong  Project`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-01 13:37 UTC, tresorsawasawa reviewed
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @MMhaidari and @Stephen-Adom  
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] Kindly make sure you update your linters config as required for the project. Right now, you are supposed the to use the **[HTML-CSS-JS](https://github.com/microverseinc/linters-config/tree/master/html-css-js)** linters but I noticed that you are still using the **HTML-CSS** linters. I suggest you refer this ****[HTML-CSS-JS](https://github.com/microverseinc/linters-config/tree/master/html-css-js)****, as it containes all info about the **[HTML-CSS-JS](https://github.com/microverseinc/linters-config/tree/master/html-css-js)** configuration.

- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 13:37 UTC, tresorsawasawa commented on app.js
> +});
- [ ] As required for the project, kindly make sure if a user submits the contact form with the email field containing uppercase characters an error message is showed up and the form cannot be sent. Right now, your app sends the form for both cases(with email in `lowercase` and in `uppercase`). Please fix that.

2023-02-01 13:37 UTC, tresorsawasawa commented on app.js
> +    error.innerHTML = 'Please enter email in lowercase';
- [ **OPTIONAL** ] **RECOMMENDED:** Good job displaying your error message close to the **submit** button. But I think it would be better you displays it between the `textarea` field and the `Submit` button, so even if the didn't scroll the entire page till the bottom, he will sill see the error message.
You can only move your `<span class="error"></span>` tag to come before the `submit` buttton

2023-02-01 13:37 UTC, tresorsawasawa commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] I think it would be better if you fix the broken `[MIT](./LICENSE)` link in your README file to make it more professional as it shows a **404** error page once clicked. And to fix that, you can only create a new file name `LICENSE` in your root directory and get its content from this **[template](https://github.com/microverseinc/readme-template/blob/master/MIT.md)** or rename this `[MIT](./LICENSE)` to `[MIT](./MIT.md)`, then the created file in your directory name it `MIT.md` and use the same content in this **[template](https://github.com/microverseinc/readme-template/blob/master/MIT.md)**

2023-02-01 16:36 UTC, MMhaidari commented
# what is added new 
- new linter added for HTML & CSS and JS
- form validation problem was solved and now it is working properly
-  READme file updated

2023-02-01 18:09 UTC, huseyinbiyik requested changes
Hi team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Github flow followed 👌
- PR description is descriptive 📝

## Required Changes ♻️
**- As the previous reviewer requested, please add a software license and make sure license link on your README works fine.** 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML"
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 03:21 UTC, tresorsawasawa requested changes

2023-02-02 03:21 UTC, tresorsawasawa commented on README.md
.

2023-02-02 05:38 UTC, MMhaidari commented
# what is added new 
- License is added newly to READme file

2023-02-02 05:49 UTC, Davidosky007 approved these changes
Hi @MMhaidari 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Good looking readme file 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 05:50 UTC, merged